# https://docs.travis-ci.com/user/build-config-validation/
version: ~> 1.0

sudo: required
dist: trusty

# Those two above are for getting most recent Ubuntu at Travis
# https://docs.travis-ci.com/user/ci-environment/

language: node_js
node_js:
  - "16"
cache:
  directories:
    - node_modules
jobs:
  fast_finish: true
script:
  - npm run lint
  - npm test
after_script: "npm run coverage"
